### PR TITLE
Fix a leak in IpcOneShotServer on MacOS

### LINKED ISSUE #262: IpcOneShotServer leaks mach ports
This is a minimal example of a system resource leak:

```rust
use ipc_channel::ipc::IpcOneShotServer;

fn main() {
    loop {
        let _ = IpcOneShotServer::<()>::new().unwrap();
    }
}
```

### PR DESCRIPTION
**Pull request by mrobinson**
The code allocates a mach port and it needs to deallocate it when the
server is dropped.

Fixes #262.

### CODE REVIEW

File: src/platform/macos/mod.rs [hunk 1]
```diff
@@ -832,22 +824,26 @@ fn select(
 pub struct OsIpcOneShotServer {
     receiver: OsIpcReceiver,
     name: String,
+    #[allow(dead_code)]
```
Comment (jdm) [inline src/platform/macos/mod.rs:827]: This field looks like it's read in the destructor. Why is this necessary?

**Review by jdm — APPROVED** [review]

File: src/platform/macos/mod.rs (hunk 1 above)
Comment (mrobinson) [reply src/platform/macos/mod.rs]: Hrm. I think I was just confused at the moment that I added this. It isn't necessary. I've pushed a new version of this change that removes it.
